### ISSUE TITLE
Play a tutorial when the program starts (JONSK)

### ISSUE THREAD

**Issue by jonsk197** [Rovanion/LeapMusic#24]

**Comment by Rovanion** [comment]
How to use portaudio with libsndfile: http://music.columbia.edu/pipermail/portaudio/2004-December/004064.html

Capabilities of libsndfile: http://www.mega-nerd.com/libsndfile/#Features

**Comment by Rovanion** [comment]
https://github.com/stevedekorte/io/blob/master/modules/FindLibSndFile.cmake

**Comment by jonsk197** [comment]
http://www.mega-nerd.com/libsndfile/api.html#open

**Comment by jonsk197** [comment]
The sound part of the tutorial need to be implemented.
