### ISSUE TITLE
Add visual interaction(hand position) (ROV)

### ISSUE THREAD

**Issue by Rovanion** [Rovanion/LeapMusic#4]
The user should be able to see a visual representation of their interaction with the instrument on their screen. It might just be a white dot on a black background, but it should be something.

**Comment by jonsk197** [comment]
Fix a note that represents the hand. It shall change color if the recorded is on or not.

**Comment by Rovanion** [comment]
The hand is now represented by a bunny/note on screen. This model changes color as the player plays and records from white to green to red respectively.
